language: node_js
node_js:
  - "node"  # latest stable release

script: yarn unit

cache:
  directories:
    - "node_modules"
  yarn: true

# enable headless Chrome
sudo: required
addons:
  chrome: stable
